<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="theme-color" content="#f8f9ff">
    <title>Admin Dashboard | TimeTrack</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24..48,400..700,0..1,-50..200&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="admin-page">
    <aside class="admin-sidebar"><div><div class="admin-brand"><img src="{{ asset('images/timetrack-logo.svg') }}" alt="TimeTrack logo"><div><strong>TimeTrack</strong><small>Admin Portal</small></div></div><div class="gps-status"><i></i>GPS Live Verification <b>Active</b></div><nav class="admin-nav"><a href="{{ url('/admin') }}"><span class="material-symbols-outlined">grid_view</span>Dashboard</a><a href="{{ route('admin.live') }}"><span class="material-symbols-outlined">radar</span>Live Attendance Feed</a><a href="{{ url('/admin/employees') }}"><span class="material-symbols-outlined">badge</span>Employee Directory</a><a href="{{ route('admin.geofence') }}"><span class="material-symbols-outlined">share_location</span>Geofence &amp; Sites</a><a id="shift-schedules-link" data-path="shifts-and-schedules" href="{{ route('admin.shifts') }}" onclick="window.location.href=this.href; return false;"><span class="material-symbols-outlined">calendar_month</span>Shifts &amp; Schedules</a><a href="{{ route('admin.reports') }}"><span class="material-symbols-outlined">query_stats</span>Attendance Reports</a><a href="{{ route('admin.settings') }}"><span class="material-symbols-outlined">admin_panel_settings</span>Settings &amp; Audit Logs</a></nav></div><div class="system-status"><span class="material-symbols-outlined">verified</span><div><strong>System Status</strong><small>All Operational</small></div><i></i></div></aside>
    <div class="admin-shell"><header class="admin-header"><div class="admin-context"><span class="material-symbols-outlined teal-text">hub</span><strong>Metro Logistics Operations</strong><span>/</span><span>All Hubs</span><small>Today · Pay Period 04</small></div><div class="admin-header-actions"><label class="admin-search"><span class="material-symbols-outlined">search</span><input id="employee-search" type="search" placeholder="Search employee, badge ID..."></label><button class="admin-icon-button" aria-label="Notifications"><span class="material-symbols-outlined">notifications</span><i></i></button><div class="admin-user"><span>MV</span><div><strong>Marcus Vance</strong><small>Operations Director</small></div></div></div></header>
        <main class="admin-main"><div class="admin-title-row"><div><div class="admin-title"><span class="material-symbols-outlined">verified_user</span><h1>Workforce Attendance &amp; Real-Time Monitoring</h1></div><p><b><i></i>Live Feed Synced</b> · Monday, September 28, 2026 · Metro Operations Network (Hub A, B &amp; West)</p></div><div class="admin-actions"><button><span class="material-symbols-outlined">download</span>Export Roster</button><button class="alert-action"><span class="material-symbols-outlined">cell_tower</span>Geofence Alert</button><button class="primary-admin"><span class="material-symbols-outlined">add_circle</span>Add Manual Exception</button></div></div>
            <div class="site-chips"><label>Worksite:</label><button class="active">All Hubs (12)</button><button>Metro Hub - Bldg B (192)</button><button>West Distribution Center (144)</button><button>North Cargo Terminal (96)</button></div>
            <section class="admin-metrics"><article><div>Total Workforce <span class="material-symbols-outlined">groups</span></div><strong>482</strong><small class="teal-text">↑ +12 staff onboarded MTD</small></article><article><div>Present Today <span class="material-symbols-outlined teal-text">how_to_reg</span></div><strong>438 <small class="teal-text">90.8%</small></strong><i class="admin-progress"><b style="width:90.8%"></b></i></article><article><div>Currently On Site <i class="live-pulse"></i></div><strong class="rose-text">394</strong><small>Actively logged &amp; in geofence</small></article><article><div>Late Arrivals <span class="material-symbols-outlined">schedule</span></div><strong>18 <small>Avg +12m</small></strong><small>3.7% grace threshold exceeded</small></article><article class="absence-metric"><div>Unscheduled Absences <span class="material-symbols-outlined">person_off</span></div><strong>26 <small>8 Pending Notes</small></strong><small>18 unaccounted / silent roster</small></article></section>
            <section class="admin-insights"><article class="punch-chart"><div class="admin-card-heading"><div><h2>Punch Velocity</h2><small>Hourly distribution · Today</small></div><span>09:00 - 11:00 peak</span></div><div class="chart-area"><div class="chart-bars"><i style="height:18%"></i><i style="height:34%"></i><i style="height:58%"></i><i class="peak" style="height:92%"></i><i style="height:76%"></i><i style="height:42%"></i><i style="height:28%"></i><i style="height:18%"></i><i style="height:12%"></i></div><div class="chart-labels"><span>06:00</span><span>08:00</span><span>10:00</span><span>12:00</span><span>14:00</span><span>16:00</span><span>18:00</span></div></div></article><article class="live-feed" id="live-feed"><div class="admin-card-heading"><div><h2>Live Attendance Feed</h2><small>Latest verified events</small></div><b>Live</b></div><div class="feed-item"><span class="feed-avatar">AR</span><div><strong>Alex Rivera <small>EMP-08241</small></strong><p>Clocked in · Hub B</p></div><time>09:42 AM</time></div><div class="feed-item"><span class="feed-avatar green-avatar">EP</span><div><strong>Elena Park <small>EMP-09120</small></strong><p>GPS verified · North Terminal</p></div><time>09:39 AM</time></div><div class="feed-item"><span class="feed-avatar gold-avatar">MB</span><div><strong>Marcus Brody <small>EMP-07431</small></strong><p>Selfie matched · West Center</p></div><time>09:32 AM</time></div></article></section>
            <section class="admin-panel exceptions" id="audit"><div class="admin-card-heading"><div><h2>Exceptions Requiring Review</h2><small>Prioritized by operational risk</small></div><b class="error-badge">3 Open</b></div><div class="exception-row"><span class="material-symbols-outlined error-text">wrong_location</span><div><strong>Carlos Mendoza · Out of bounds</strong><small>210m outside Hub B · Liveness review 94.2%</small></div><button>Review</button></div><div class="exception-row"><span class="material-symbols-outlined amber-text">schedule</span><div><strong>Elena Rostova · Late arrival</strong><small>14 minutes late · Supervisor note pending</small></div><button class="neutral-review">Review</button></div></section>
            <section class="admin-panel roster-panel" id="employees"><div class="admin-card-heading"><div><h2>Live Workforce Roster</h2><small>Real-time presence and verification state</small></div><a href="#employees">View Directory <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="roster-table-wrap"><table class="roster-table"><thead><tr><th>Employee</th><th>Shift</th><th>Time In</th><th>Duration</th><th>Location</th><th>Verification</th><th>Status</th></tr></thead><tbody><tr><td><strong>Alex Rivera</strong><small>EMP-08241 · Fleet Logistics</small></td><td>Morning Shift A<small>09:00 - 18:00</small></td><td>08:58 AM</td><td>6h 42m</td><td><span class="location-tag">Hub B (12m in)</span></td><td class="teal-text">✓ 99.4% Verified</td><td><span class="present-tag">Present · On-Time</span></td></tr><tr><td><strong>Elena Rostova</strong><small>EMP-09120 · Fleet Logistics</small></td><td>Morning Shift A<small>09:00 - 18:00</small></td><td>09:14 AM <em>+14m</em></td><td>6h 15m</td><td><span class="location-tag">Hub B (38m in)</span></td><td class="teal-text">✓ 99.7% Verified</td><td><span class="late-tag">Late (+14m)</span></td></tr><tr class="needs-review"><td><strong>Carlos Mendoza</strong><small>EMP-06319 · Freight Handling</small></td><td>Morning Shift A<small>09:00 - 18:00</small></td><td class="error-text">09:28 AM ⚠</td><td>6h 02m</td><td><span class="out-tag">Out of Bounds (210m)</span></td><td>⚠ 94.2% Liveness Review</td><td><button class="review-button">Action Required</button></td></tr><tr><td><strong>David Kim</strong><small>EMP-05118 · Heavy Equipment</small></td><td>Morning Shift A<small>09:00 - 18:00</small></td><td>--:--</td><td>0h 00m</td><td>No Signal</td><td>Pending</td><td><span class="absent-tag">Unexcused Absent</span></td></tr></tbody></table></div><div class="roster-footer">Showing <strong>1 - 4</strong> of <strong>482</strong> active roster personnel <span>‹ Previous &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; Next ›</span></div></section>
        </main>
    </div>
    <script src="{{ asset('js/app.js') }}?v=20260933"></script>
<script>
  document.querySelectorAll('.admin-title-row, .site-chips, .admin-metrics, .admin-insights, .admin-panel').forEach(function (section) {
    section.remove();
  });
  var adminMain = document.querySelector('.admin-main');
  if (adminMain) {
    adminMain.insertAdjacentHTML('beforeend', '<section class="admin-panel empty-state"><div class="admin-title"><span class="material-symbols-outlined">verified_user</span><h1>Workforce Attendance</h1></div><p>Your business workspace is ready. No sample employees or attendance records are shown.</p><a class="primary-admin" href="{{ route('admin.employees.create') }}"><span class="material-symbols-outlined">person_add</span>Register First Employee</a></section>');
  }
</script>
</body>
</html>
