<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, viewport-fit=cover"><meta name="theme-color" content="#fff8f7">
    <title>Attendance History | TimeTrack</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="history-page">
    <header class="history-header"><a class="back-button" href="{{ route('attendance') }}" aria-label="Back"><span class="material-symbols-outlined">arrow_back</span></a><img src="{{ asset('images/timetrack-logo.svg') }}" alt="TimeTrack logo"><div><strong>TimeTrack</strong><small>History <i></i></small></div><button class="round-button" type="button" aria-label="Sync status"><span class="material-symbols-outlined">cloud_done</span></button><span class="profile-avatar">AT</span></header>
    <main class="history-main">
        <section class="history-toolbar"><div class="month-row"><button id="prev-month" aria-label="Previous month"><span class="material-symbols-outlined">chevron_left</span></button><strong><span class="material-symbols-outlined">calendar_today</span><span id="month-label">September 2026</span></strong><button id="next-month" aria-label="Next month"><span class="material-symbols-outlined">chevron_right</span></button><button class="export-button" id="open-export-modal"><span class="material-symbols-outlined">sim_card_download</span>Export</button></div><div class="history-filters"><button class="history-filter active" data-filter="all">All <b>22</b></button><button class="history-filter" data-filter="ontime"><i class="green-dot"></i>On Time <b>20</b></button><button class="history-filter" data-filter="late"><i class="amber-dot"></i>Late <b>1</b></button><button class="history-filter" data-filter="pending"><i class="rose-dot"></i>Pending <b>1</b></button></div></section>
        <section class="history-metrics"><article><div>Days Present <span class="material-symbols-outlined">how_to_reg</span></div><strong>20<small>/ 21 workdays</small></strong><i class="metric-progress"><b></b></i></article><article><div>On-Time Rate <span class="material-symbols-outlined green-text">verified</span></div><strong class="green-text">95.2%</strong><small class="green-text">↑ Top 5% Fleet</small></article><article><div>Total Hours <span class="material-symbols-outlined">schedule</span></div><strong>168.5<small> hrs</small></strong><small>Target: 168.0 hrs</small></article><article class="overtime"><div>Overtime <span class="material-symbols-outlined">alarm_add</span></div><strong>8.5<small> hrs OT</small></strong><small>Approved by HQ</small></article></section>
        @php($latestRecord = session('attendance_records', [])[0] ?? null)
        <section class="activity-section"><div class="activity-heading"><h2>Activity Log</h2><span>Showing latest verified</span></div>
            @if ($latestRecord)
            <article class="history-record" data-status="ontime"><div class="record-main"><div class="record-heading"><div><h3>{{ $latestRecord['date'] }} <i class="live-dot"></i></h3><small>Regular Shift · 09:00 AM - 06:00 PM</small></div><b class="record-status approved-status">Completed</b></div><div class="record-times"><div><small>Punch In</small><strong><span class="material-symbols-outlined rose-text">login</span>{{ $latestRecord['time_in'] }}</strong></div><div><small>Punch Out</small><strong><span class="material-symbols-outlined">logout</span>{{ $latestRecord['time_out'] }}</strong></div></div><div class="record-tags"><span>GPS Match</span><span class="green-tag">◉ Selfie Matched</span></div></div></article>
            @endif
            <article class="history-record" data-status="pending"><div class="record-main"><div class="record-heading"><div><h3>Today, Sep 28 <i class="live-dot"></i></h3><small>Regular Shift · 09:00 AM - 06:00 PM</small></div><b class="record-status pending-status">In Progress</b></div><div class="record-times"><div><small>Punch In</small><strong><span class="material-symbols-outlined rose-text">login</span>09:00 AM</strong></div><div><small>Punch Out</small><strong class="muted-time"><span class="material-symbols-outlined">logout</span>--:-- (Active)</strong></div></div><div class="record-tags"><span>📍 HQ Hub (+/- 8m)</span><span class="green-tag">◉ Selfie Matched</span></div><button class="accordion-trigger" data-toggle="history-record-1"><span>Show Verification Audit</span><span class="material-symbols-outlined">expand_more</span></button></div><div class="record-drawer" id="drawer-history-record-1"><div><strong>Face Vector Hash #9102-AC</strong><b>99.4% Confidence</b></div><small>Captured via secure device · Audit Cert: 0x82f...a109</small><div class="drawer-map">Radar boundary locked · HQ campus</div></div></article>
            <article class="history-record" data-status="ontime"><div class="record-main"><div class="record-heading"><div><h3>Fri, Sep 25</h3><small>Regular Shift · 09:00 AM - 05:00 PM</small></div><b class="record-status approved-status">8h 08m</b></div><div class="record-times"><div><small>In</small><strong><span class="material-symbols-outlined green-text">check</span>08:58 AM</strong></div><div><small>Out</small><strong><span class="material-symbols-outlined">logout</span>05:06 PM</strong></div></div><div class="record-tags"><span class="green-tag">◉ GPS Match (Within 45m)</span><span class="green-tag">◉ Selfie Match</span></div><button class="accordion-trigger" data-toggle="history-record-2"><span>View Audit Credentials</span><span class="material-symbols-outlined">expand_more</span></button></div><div class="record-drawer" id="drawer-history-record-2"><div><strong>Biometric Signoff</strong><b>08:58:12 AM</b></div><small>Encrypted SHA-256 validated · Secure Terminal Fleet 12</small></div></article>
            <article class="history-record" data-status="late"><div class="record-main"><div class="record-heading"><div><h3>Thu, Sep 24 <span class="material-symbols-outlined amber-text">info</span></h3><small>Shift Start Target: 09:00 AM</small></div><b class="record-status late-status">Late (7m)</b></div><div class="record-times"><div><small>Clock In</small><strong class="amber-text"><span class="material-symbols-outlined">schedule</span>09:07 AM</strong></div><div><small>Clock Out</small><strong><span class="material-symbols-outlined">logout</span>06:10 PM</strong></div></div><div class="exception-note"><span class="material-symbols-outlined">edit_note</span>Traffic delay logged &amp; acknowledged</div><div class="record-tags"><span>📍 Within 60m geofence</span><span>✓ Supervisor Approved</span></div><button class="accordion-trigger" data-toggle="history-record-3"><span>Show Exception Ticket</span><span class="material-symbols-outlined">expand_more</span></button></div><div class="record-drawer" id="drawer-history-record-3"><div><strong>Incident Ticket #INC-8831</strong><b class="green-text">Resolution: Excused</b></div><small>Auto-routed to supervisor. No penalty deducted.</small></div></article>
        </section>
    </main>
    <div class="export-sheet" id="export-sheet"><div class="export-modal"><button class="close-export" id="close-export-modal" aria-label="Close"><span class="material-symbols-outlined">close</span></button><h2>Download Timesheet</h2><p>Period: September 01 - September 30, 2026</p><div class="export-options"><label><input type="radio" name="format" value="pdf" checked><span class="material-symbols-outlined">picture_as_pdf</span><strong>Formal PDF Report</strong><small>Signed official audit certificate</small></label><label><input type="radio" name="format" value="csv"><span class="material-symbols-outlined green-text">csv</span><strong>Raw CSV / Excel</strong><small>Includes granular GPS coordinates</small></label></div><button id="confirm-download-btn" class="confirm-export"><span class="material-symbols-outlined">download</span>Generate &amp; Download</button></div></div><div class="history-toast" id="toast-banner"><span class="material-symbols-outlined green-text">check_circle</span><span id="toast-text">Timesheet downloaded successfully</span></div>
    <nav class="bottom-nav"><a href="{{ route('attendance') }}"><span class="material-symbols-outlined">schedule</span>Attendance</a><a class="active" href="{{ url('/history') }}"><span class="material-symbols-outlined">calendar_month</span>History</a><a href="{{ url('/verify') }}"><span class="material-symbols-outlined">document_scanner</span>Verify</a><a href="{{ url('/profile') }}"><span class="material-symbols-outlined">badge</span>Profile</a></nav>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>
