<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, viewport-fit=cover">
    <meta name="theme-color" content="#fff8f7">
    <title>Attendance | TimeTrack</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
    @php($employee = session('authenticated_employee', session('registered_employee', ['full_name' => 'Alexandre Tan', 'job_title' => 'Senior Operations Specialist', 'email' => 'alexandre.tan@timetrack.enterprise', 'worksite' => 'Metro Logistics Hub - Bldg B'])))
    @php($isClockedIn = session()->has('time_in') && !session()->has('time_out'))
    @php($timeIn = session('time_in'))
    @php($timeOut = session('time_out'))
    <header class="mobile-header">
        <div class="brand-lockup"><img src="{{ asset('images/timetrack-logo.svg') }}" alt="TimeTrack logo" class="brand-mark"><div><strong>TimeTrack</strong><span>Attendance <i class="online-dot"></i></span></div></div>
        <div class="header-actions"><button class="round-button" type="button" aria-label="Sync status" title="Synced"><span class="material-symbols-outlined">cloud_done</span></button><span class="profile-avatar">AT</span></div>
    </header>
    <main class="dashboard-main">
        <section class="employee-card"><div class="employee-row"><div class="employee-avatar">{{ collect(explode(' ', $employee['full_name']))->map(fn($part) => strtoupper(substr($part, 0, 1)))->take(2)->join('') }}<span class="verified-badge material-symbols-outlined">verified</span></div><div class="employee-info"><div class="employee-name-row"><h1>{{ $employee['full_name'] }}</h1><span class="employee-id">{{ $employee['email'] }}</span></div><p>{{ $employee['job_title'] }}</p><small>{{ $employee['worksite'] }} · Shift A (09:00 - 18:00)</small></div></div><div class="geofence-pill"><span class="pulse-dot"></span><span class="material-symbols-outlined">location_on</span><strong>{{ $employee['worksite'] }}</strong><b>• In Geofence</b><em>42m away</em></div></section>
        <section class="clock-card"><div class="clock-top"><span><span class="material-symbols-outlined">calendar_today</span><span id="current-date">Monday, September 28, 2026</span></span><b><i></i> GPS Synced</b></div><div class="clock-display"><strong id="live-clock">09:42:15</strong><span id="live-period">AM</span></div><div class="clock-status"><span class="material-symbols-outlined">timer_off</span>Not Clocked In</div></section>
        <section class="punch-area"><form action="{{ $isClockedIn ? route('time-out') : route('time-in') }}" method="POST">@csrf<button id="punch-button" class="punch-button {{ $isClockedIn ? 'punch-timeout' : '' }}" type="submit"><span class="punch-icon material-symbols-outlined">{{ $isClockedIn ? 'logout' : 'fingerprint' }}</span><span class="punch-copy"><strong id="punch-label">{{ $isClockedIn ? 'TIME OUT NOW' : 'TIME IN NOW' }}</strong><small>{{ $isClockedIn ? 'Requires Time Out Verification' : 'Requires Live Selfie + GPS Check' }}</small></span><span class="punch-arrow material-symbols-outlined">arrow_forward</span></button></form><div class="punch-requirements"><span><i class="material-symbols-outlined">check_circle</i>{{ $isClockedIn ? 'Time In Recorded' : 'Face Verification Ready' }}</span><span>•</span><span><i class="material-symbols-outlined">my_location</i>Precise Radar Active</span></div></section>
        <section class="summary-grid"><article class="summary-card"><div><span>Time In</span><i class="material-symbols-outlined rose">login</i></div><strong>--:--</strong><small><i></i> Pending punch</small></article><article class="summary-card"><div><span>Time Out</span><i class="material-symbols-outlined mauve">logout</i></div><strong>--:--</strong><small>Scheduled 18:00</small></article><article class="summary-card"><div><span>Shift Target</span><i class="material-symbols-outlined pink">timelapse</i></div><strong>8h 00m</strong><div class="progress"><i></i></div></article><article class="summary-card"><div><span>Total Logged</span><i class="material-symbols-outlined green">hourglass_top</i></div><strong>0h 00m</strong><small>0% of shift goal</small></article></section>
        <section class="diagnostics-card"><div class="section-heading"><h2><span class="material-symbols-outlined rose-text">radar</span>Location &amp; Geofence Diagnostics</h2><b>Active</b></div><div class="diagnostic-item"><span class="material-symbols-outlined green-text">verified_user</span><div><strong>Workplace Geofence Authorized</strong><small>Metro Logistics Hub · 100m designated radius</small></div></div><div class="diagnostic-item"><span class="material-symbols-outlined rose-text">satellite_alt</span><div><strong>GPS High Precision Lock</strong><small>Accuracy: ±3 meters · Triangulated via 12 satellites</small></div></div></section>
        <section class="recent-section" id="history"><div class="section-heading"><h2>Recent Logs</h2><a href="#history">View All <span class="material-symbols-outlined">chevron_right</span></a></div><article class="recent-card"><div class="recent-top"><div class="recent-title"><span class="history-icon material-symbols-outlined">history</span><div><strong>Yesterday</strong><small>Wed, September 25, 2026</small></div></div><b>8h 37m</b></div><div class="recent-details"><div><span class="material-symbols-outlined green-text">check_circle</span><small>In: 08:55 AM<strong>Biometric Verified</strong></small></div><div><span class="material-symbols-outlined green-text">check_circle</span><small>Out: 05:32 PM<strong>Biometric Verified</strong></small></div></div></article></section>
        <section class="generator-card" id="reports"><div class="section-heading"><h2>Workforce note</h2></div><p>Prepare a starter note for your team workflow.</p>@if ($errors->any())<div class="form-alert">{{ $errors->first('business_type') }}</div>@endif<form action="{{ url('/generate') }}" method="POST"><label for="business_type">Business or team type</label><div><input id="business_type" name="business_type" type="text" value="{{ old('business_type') }}" required maxlength="255" placeholder="e.g. Retail operations"><button type="submit">Generate</button></div>@csrf</form></section>
    </main>
    <nav class="bottom-nav"><a class="active" href="{{ route('attendance') }}"><span class="material-symbols-outlined">schedule</span>Attendance</a><a href="{{ url('/history') }}"><span class="material-symbols-outlined">calendar_month</span>History</a><a href="{{ url('/verify') }}"><span class="material-symbols-outlined">document_scanner</span>Verify</a><a href="{{ url('/profile') }}"><span class="material-symbols-outlined">badge</span>Profile</a></nav>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>
