<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Time Out Verification | TimeTrack</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap" rel="stylesheet"></head>
<body class="verify-page">
@php($employee = session('authenticated_employee', session('registered_employee', ['full_name' => 'Employee', 'email' => '', 'worksite' => 'Assigned worksite'])))
@php($timeIn = session('time_in', ['display' => '--:--']))
@php($timeOut = session('time_out', ['display' => now('Asia/Singapore')->format('h:i:s A')]))
<header class="verify-header"><a class="back-button" href="{{ route('attendance') }}"><span class="material-symbols-outlined">arrow_back</span></a><img src="{{ asset('images/timetrack-logo.svg') }}" alt="TimeTrack logo"><h1>Time Out Verification</h1><span class="profile-avatar">AT</span></header>
<main class="verify-main"><section class="step-card"><div class="section-heading"><h2>Verification Step 3 of 3</h2><b><span class="material-symbols-outlined">lock</span>Final Review</b></div><div class="steps"><div><span class="done material-symbols-outlined">check</span><small>1. Face ID</small></div><div><span class="done material-symbols-outlined">check</span><small>2. Geofence</small></div><div><span class="current material-symbols-outlined">verified</span><small>3. Confirm</small></div></div></section>
<section class="audit-banner"><span class="material-symbols-outlined">event_available</span><div><strong>Shift Conclusion Summary</strong><p>{{ $employee['full_name'] }} · Time Out recorded at {{ $timeOut['display'] }}.</p></div></section>
<section class="verify-card"><div class="verify-card-heading"><h2><span class="material-symbols-outlined rose-text">badge</span>Biometric Photo ID</h2><b><i></i>Live Verified</b></div><div class="timeout-summary"><span class="material-symbols-outlined">face</span><div><strong>{{ $employee['full_name'] }}</strong><small>99.4% Match · Liveness Confirmed</small></div><button class="face-guide" type="button"><span class="material-symbols-outlined">flip_camera_ios</span>Retake</button></div></section>
<section class="verify-card"><div class="verify-card-heading"><h2><span class="material-symbols-outlined green-text">location_on</span>Authorized Work Site</h2><b class="location-badge"><span class="material-symbols-outlined">check_circle</span>In Perimeter</b></div><div class="map-preview"><div class="map-lines"></div><div class="geofence-ring"><span class="map-ping"></span><span class="map-dot"></span><b>150m Geofence</b></div><div class="distance-badge"><span class="material-symbols-outlined green-text">navigation</span>Accuracy: ±3m · Within Bound <strong>GPS Active</strong></div></div><div class="workplace-row"><span class="material-symbols-outlined">apartment</span><div><strong>{{ $employee['worksite'] }}</strong><small>Assigned worksite · Geofence Radius: 150m</small></div><span class="material-symbols-outlined green-text">check_circle</span></div></section>
<section class="verify-card"><div class="verify-card-heading"><h2>Punch Out Record</h2><b class="shift-badge">Ready to Submit</b></div><div class="timeout-display"><small>Punch Action Type</small><strong>TIME OUT / CLOCK OUT</strong><b>{{ $timeOut['display'] }}</b><span>{{ now('Asia/Singapore')->format('l, M d, Y') }}</span></div><div class="timeout-meta"><span>Time In</span><strong>{{ $timeIn['display'] }} · Active shift</strong><span>Biometric Signature</span><strong class="green-text">✓ SHA-256 Verified</strong></div></section>
<section class="verify-actions"><form id="timeout-confirm-form" action="{{ route('time-out.confirm') }}" method="POST">@csrf<button id="confirm-timeout-btn" class="confirm-button" type="submit"><span class="material-symbols-outlined">logout</span>Confirm &amp; Submit Time Out</button></form><a class="retake-button" href="{{ route('attendance') }}"><span class="material-symbols-outlined">arrow_back</span>Cancel / Return to Dashboard</a></section></main>
<nav class="bottom-nav"><a href="{{ route('attendance') }}"><span class="material-symbols-outlined">schedule</span>Attendance</a><a href="{{ url('/history') }}"><span class="material-symbols-outlined">calendar_month</span>History</a><a class="active" href="{{ url('/timeout-verify') }}"><span class="material-symbols-outlined">document_scanner</span>Verify</a><a href="{{ url('/profile') }}"><span class="material-symbols-outlined">badge</span>Profile</a></nav><script src="{{ asset('js/app.js') }}"></script></body></html>
